using System.ComponentModel.DataAnnotations;

namespace UM_with_Role_Claim_Audit_log.Models.ViewModels
{
    /// <summary>
    /// View model for displaying role information in list views and forms.
    /// Used in multiple contexts:
    /// - Roles/Index: Display all roles in a table with user counts
    /// - Roles/Create: Create new role with name validation
    /// - Roles/Edit: Modify existing role name
    /// 
    /// This is a lightweight ViewModel compared to RoleDetailsViewModel which includes
    /// full user lists and claims. This model focuses on essential role information
    /// for list displays and basic CRUD operations.
    /// 
    /// Key Differences from RoleDetailsViewModel:
    /// - RoleViewModel: Lightweight (Id, Name, UserCount only) - for lists and forms
    /// - RoleDetailsViewModel: Comprehensive (includes Users list, Claims list) - for details page
    /// 
    /// Design Pattern:
    /// Follows the ViewModel-per-View principle - different views need different data shapes.
    /// This keeps data transfer minimal and improves performance for list views.
    /// </summary>
    public class RoleViewModel
    {
        /// <summary>
        /// The unique identifier of the role.
        /// Maps to AspNetRoles.Id in the database.
        /// 
        /// Usage Context:
        /// - In list view: Used to generate action links (Edit, Delete, Details)
        /// - In edit form: Hidden input to identify which role is being modified
        /// - In create form: Empty (generated by Identity system on save)
        /// 
        /// Format:
        /// Typically a GUID string (e.g., "a1b2c3d4-e5f6-7890-abcd-1234567890ab")
        /// Generated automatically by ASP.NET Core Identity when role is created.
        /// 
        /// Not displayed to end users - only used internally for routing and identification.
        /// </summary>
        public string Id { get; set; } = string.Empty;

        /// <summary>
        /// The display name of the role.
        /// Maps to AspNetRoles.Name in the database.
        /// 
        /// Validation Rules:
        /// - Required: Cannot be empty or whitespace
        /// - Unique: ASP.NET Core Identity enforces uniqueness at database level
        /// - Recommended: Use PascalCase (e.g., "ProductManager", not "product_manager")
        /// 
        /// Common Role Names:
        /// - "Admin": Full system access (bypasses all claim checks)
        /// - "Manager": Mid-level access with selected claims
        /// - "User": Basic access with minimal claims
        /// - Custom examples: "Supervisor", "Auditor", "Guest", "ContentEditor"
        /// 
        /// Display Context:
        /// - In list view: Shown as clickable link to role details
        /// - In create form: Text input for new role name
        /// - In edit form: Pre-populated text input (can be modified)
        /// 
        /// Special Considerations:
        /// - Admin role may have UI restrictions to prevent accidental renaming
        /// - Role name changes do NOT affect existing user assignments
        /// - Used in audit logs to track role-related activities
        /// 
        /// Best Practices for Buyers:
        /// - Keep role names descriptive but concise (e.g., "SalesManager" vs "SM")
        /// - Use singular form (e.g., "Editor", not "Editors")
        /// - Avoid abbreviations unless widely understood
        /// - Consider internationalization if supporting multiple languages
        /// </summary>
        [Required]
        [Display(Name = "Role Name")]
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// The total number of users currently assigned to this role.
        /// Calculated by counting entries in AspNetUserRoles table for this role.
        /// 
        /// Display Purpose:
        /// Shows how many users would be affected by role modifications.
        /// Displayed in the roles list table: "Role Name | User Count | Actions"
        /// 
        /// Usage Contexts:
        /// 
        /// 1. Role List View (Index):
        ///    - Column in table: "10 users"
        ///    - Quick overview of role popularity/usage
        ///    - Helps identify unused roles for cleanup
        /// 
        /// 2. Delete Confirmation:
        ///    - Shows impact: "This role is assigned to {UserCount} user(s)"
        ///    - When UserCount > 0: Display warning and require confirmation
        ///    - When UserCount = 0: Safe to delete without user impact
        /// 
        /// 3. Role Management Dashboard:
        ///    - Statistics: Most used roles, least used roles
        ///    - Capacity planning: User distribution across roles
        /// 
        /// Visual Indicators:
        /// - UserCount = 0: Gray badge "0 users" (safe to delete)
        /// - UserCount > 0: Blue badge "{count} users" (caution on delete)
        /// - UserCount > 50: Warning icon (high-impact role)
        /// 
        /// Performance Note:
        /// Calculated efficiently with COUNT() query rather than loading all users.
        /// For very large systems (1000+ users per role), consider caching this value.
        /// 
        /// Not Editable:
        /// This is a read-only calculated field - users cannot directly modify it.
        /// Changes only through user-role assignments in Users/Edit or AssignRole pages.
        /// </summary>
        public int UserCount { get; set; }
    }
}