namespace UM_with_Role_Claim_Audit_log.Models
{
    /// <summary>
    /// Entity model for storing audit trail records in the database.
    /// Tracks all significant user actions and system events for security, compliance, and troubleshooting.
    /// 
    /// Purpose:
    /// Provides a complete audit trail of who did what, when, and with what details.
    /// Essential for:
    /// - Security monitoring: Detect unauthorized access or suspicious activities
    /// - Compliance: Meet regulatory requirements (GDPR, SOC 2, HIPAA, etc.)
    /// - Troubleshooting: Investigate issues by reviewing historical actions
    /// - Accountability: Track administrative changes to users, roles, and permissions
    /// - Forensics: Post-incident analysis and investigation
    /// 
    /// Database Mapping:
    /// - Table: AuditLogs
    /// - Primary Key: Id (auto-increment integer)
    /// - No foreign key constraints (UserId stored as string for flexibility)
    /// - Indexes recommended: UserId, Timestamp, Action (for query performance)
    /// 
    /// Logged Actions Include:
    /// - User management: "User Created", "User Updated", "User Deleted", "Password Reset"
    /// - Role management: "Role Created", "Role Updated", "Role Deleted", "User Role Assigned"
    /// - Claims management: "User Claims Updated", "Role Claims Updated"
    /// - Authentication: "Login Successful", "Login Failed", "Account Locked"
    /// - Any other critical system operations
    /// 
    /// Data Retention:
    /// Consider implementing retention policies:
    /// - Keep recent logs (e.g., last 90 days) in main table for fast access
    /// - Archive older logs to separate table or storage for compliance
    /// - Implement auto-cleanup job to prevent unlimited growth
    /// 
    /// Access Control:
    /// Access to audit logs should be restricted to users with CanViewAuditLogs claim.
    /// Audit logs themselves should be immutable (no edit/delete functionality in UI).
    /// 
    /// Related Files:
    /// - AuditLogService.cs: Business logic for creating audit log entries
    /// - AuditLogsController.cs: Display audit logs to authorized users
    /// - AuditLogViewModel.cs: ViewModel for displaying logs with user email resolution
    /// </summary>
    public class AuditLog
    {
        /// <summary>
        /// Unique identifier for the audit log entry.
        /// Auto-generated by database (Identity column in SQL Server).
        /// 
        /// Purpose:
        /// - Primary key for the AuditLogs table
        /// - Used for pagination and record identification
        /// - Ensures each log entry has a unique identifier
        /// 
        /// Type: int (4-byte integer)
        /// Auto-increment starts at 1, increments by 1 for each new record.
        /// 
        /// Not exposed to end users in UI - used internally for database operations.
        /// In views, logs are typically sorted by Timestamp (most recent first), not by Id.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// The unique identifier of the user who performed the action.
        /// Maps to AspNetUsers.Id but stored as string without foreign key constraint.
        /// 
        /// Purpose:
        /// Links the audit log entry to the user account responsible for the action.
        /// Enables querying: "Show all actions performed by user X"
        /// 
        /// Data Type: string (not GUID)
        /// Matches ASP.NET Core Identity's default user ID format.
        /// Typically contains a GUID string (e.g., "a1b2c3d4-e5f6-7890-abcd-1234567890ab")
        /// 
        /// Why No Foreign Key?
        /// - Allows logging actions by deleted users (historical data preserved)
        /// - Enables logging system actions with special UserId values (e.g., "System", "Anonymous")
        /// - Prevents cascade delete issues (deleting user doesn't delete audit logs)
        /// - Audit logs remain intact even if user account is removed
        /// 
        /// Special Values:
        /// - Normal user: GUID string from AspNetUsers.Id
        /// - System actions: "System" (e.g., automated tasks, background jobs)
        /// - Anonymous: "Anonymous" (e.g., public registration attempts)
        /// - Unknown: "Unknown" (fallback if user context unavailable)
        /// 
        /// Display Resolution:
        /// In AuditLogsController, this UserId is resolved to user email via UserManager:
        /// var user = await _userManager.FindByIdAsync(log.UserId);
        /// var email = user?.Email ?? "Unknown";
        /// 
        /// This enables human-readable audit logs: "john.doe@company.com created a new role"
        /// rather than: "a1b2c3d4... created a new role"
        /// 
        /// Query Examples:
        /// - Find all actions by specific user: WHERE UserId = @userId
        /// - Find actions by deleted users: WHERE UserId NOT IN (SELECT Id FROM AspNetUsers)
        /// - Find system actions: WHERE UserId = 'System'
        /// 
        /// Security Note:
        /// UserId should NEVER be modified after audit log creation (immutable).
        /// Any tampering with audit logs undermines their integrity and compliance value.
        /// </summary>
        public string UserId { get; set; } = string.Empty;

        /// <summary>
        /// Brief description of the action that was performed.
        /// Standardized action names for consistent logging and filtering.
        /// 
        /// Purpose:
        /// - Categorize log entries for filtering and searching
        /// - Enable statistics: "How many password resets this month?"
        /// - Support alert triggers: "Alert when Action = 'Account Locked'"
        /// 
        /// Recommended Action Names (Standardized):
        /// 
        /// User Management:
        /// - "User Created" - New user account created
        /// - "User Updated" - User profile or settings modified
        /// - "User Deleted" - User account removed
        /// - "Password Reset" - Admin reset user's password
        /// - "Account Locked" - User account locked out
        /// - "Account Unlocked" - User account unlocked by admin
        /// 
        /// Role Management:
        /// - "Role Created" - New role created
        /// - "Role Updated" - Role name or settings modified
        /// - "Role Deleted" - Role removed from system
        /// - "User Role Assigned" - Role assigned to user
        /// - "User Role Removed" - Role removed from user
        /// 
        /// Claims Management:
        /// - "User Claims Updated" - User's direct claims modified
        /// - "Role Claims Updated" - Role's claims modified (affects all users in role)
        /// 
        /// Authentication Events:
        /// - "Login Successful" - User logged in successfully
        /// - "Login Failed" - Failed login attempt (wrong password)
        /// - "Logout" - User logged out
        /// 
        /// Best Practices:
        /// - Use consistent naming (PascalCase or sentence case)
        /// - Keep action names concise but descriptive
        /// - Avoid including variable data in action name (use Details property instead)
        /// - Use past tense ("Created" not "Create")
        /// 
        /// Display in UI:
        /// Shown in audit log table as "Action" column.
        /// Can be used for filtering: "Show only 'Password Reset' actions"
        /// 
        /// Searchability:
        /// Indexed for fast filtering by action type.
        /// Supports queries like: SELECT * FROM AuditLogs WHERE Action = 'User Deleted'
        /// </summary>
        public string Action { get; set; } = string.Empty;

        /// <summary>
        /// The date and time when the action was performed.
        /// Recorded in UTC for consistency across timezones.
        /// 
        /// Purpose:
        /// - Chronological ordering of events (most recent first in UI)
        /// - Time-based filtering: "Show logs from last 7 days"
        /// - Compliance: Prove when actions occurred
        /// - Troubleshooting: Correlate actions with system issues
        /// - Analytics: Activity patterns over time
        /// 
        /// Data Type: DateTime
        /// Stored as UTC (Coordinated Universal Time) to avoid timezone ambiguity.
        /// In AuditLogService.cs: Timestamp = DateTime.UtcNow
        /// 
        /// Why UTC?
        /// - Consistent across all users regardless of timezone
        /// - Avoids daylight saving time issues
        /// - Standard practice for server-side timestamps
        /// - Can be converted to user's local timezone in UI if needed
        /// 
        /// Display Format:
        /// In UI, convert to user-friendly format:
        /// - Absolute: "2025-12-29 14:30:45 UTC"
        /// - Relative: "2 hours ago", "Yesterday", "Last week"
        /// - Local: Convert to user's timezone for display
        /// 
        /// Indexing:
        /// Timestamp column should be indexed for performance:
        /// - Fast sorting: ORDER BY Timestamp DESC
        /// - Fast filtering: WHERE Timestamp >= @startDate AND Timestamp <= @endDate
        /// - Pagination: Efficient OFFSET/FETCH operations
        /// 
        /// Query Examples:
        /// - Recent logs: WHERE Timestamp >= DATEADD(day, -7, GETUTCDATE())
        /// - Date range: WHERE Timestamp BETWEEN @start AND @end
        /// - Activity timeline: GROUP BY CAST(Timestamp AS DATE)
        /// 
        /// Retention Policy:
        /// Consider archiving or deleting logs older than X days/months:
        /// - DELETE FROM AuditLogs WHERE Timestamp < DATEADD(month, -12, GETUTCDATE())
        /// - Or move to archive table for long-term storage
        /// 
        /// Immutability:
        /// Timestamp should NEVER be modified after creation.
        /// Changing timestamps undermines audit trail integrity.
        /// </summary>
        public DateTime Timestamp { get; set; }

        /// <summary>
        /// Additional context and information about the action.
        /// Free-form text field for storing action-specific details.
        /// 
        /// Purpose:
        /// - Provide context beyond the action name
        /// - Store variable data (e.g., which user was affected, what changed)
        /// - Enable detailed forensic analysis
        /// - Support troubleshooting with specific information
        /// 
        /// Content Examples:
        /// 
        /// User Management:
        /// - "Created user: john.doe@company.com"
        /// - "Updated user: jane.smith@company.com. Changed email from old@email.com to new@email.com"
        /// - "Deleted user: obsolete@company.com"
        /// - "Admin reset password for user: help@company.com"
        /// 
        /// Role Management:
        /// - "Created role: ProductManager"
        /// - "Updated role name from 'Manager' to 'SeniorManager'"
        /// - "Deleted role: TemporaryRole (had 0 users)"
        /// - "Assigned role 'Admin' to user: newadmin@company.com"
        /// 
        /// Claims Management:
        /// - "Updated claims for user: user@company.com. Claims: CanEditUsers, CanViewRoles"
        /// - "Updated claims for role: Manager. Claims: CanEditUsers, CanManageClaims, CanViewAuditLogs"
        /// 
        /// Authentication:
        /// - "User admin@company.com logged in successfully from IP 192.168.1.100"
        /// - "Failed login attempt for user: wrong@email.com (invalid password)"
        /// 
        /// Best Practices:
        /// - Include relevant identifiers (email, role name, claim type)
        /// - Be specific but concise
        /// - Avoid storing sensitive data (passwords, API keys, etc.)
        /// - Use consistent formatting for easier parsing
        /// - Include "before/after" values for update operations
        /// 
        /// Format Suggestions:
        /// - Simple: "{Action} for {EntityType}: {EntityName}"
        /// - Detailed: "{Action} for {EntityType}: {EntityName}. Changes: {ChangeDescription}"
        /// - Structured: Consider JSON format for complex details (if needed):
        ///   {"user": "john@company.com", "changes": {"email": "new@email.com"}}
        /// 
        /// Display in UI:
        /// - List view: Show truncated details (first 50-100 characters)
        /// - Details view: Show full details with line breaks
        /// - Searchable: Enable full-text search on Details column
        /// 
        /// Storage Considerations:
        /// - Data Type: string (nvarchar(MAX) or nvarchar(2000) in SQL Server)
        /// - Consider max length if using fixed-size column (e.g., nvarchar(500))
        /// - For very detailed logs, consider separate table for extended data
        /// 
        /// Privacy Considerations:
        /// - Do NOT log: Passwords, credit card numbers, SSNs, API keys
        /// - Be cautious with PII (Personally Identifiable Information) depending on compliance needs
        /// - Consider encryption at rest if storing sensitive context
        /// 
        /// Searchability:
        /// Enable admins to search logs by details:
        /// - "Show logs containing email: john@company.com"
        /// - "Find all logs mentioning role: Admin"
        /// - Consider full-text indexing for large audit log tables
        /// 
        /// Example Queries:
        /// - Search: WHERE Details LIKE '%john@company.com%'
        /// - Pattern: WHERE Details LIKE 'Created user:%'
        /// - JSON: WHERE JSON_VALUE(Details, '$.user') = 'john@company.com' (if using JSON)
        /// </summary>
        public string Details { get; set; } = string.Empty;
    }
}